spring:
  application:
    name: imageanalysis
    
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
      image:
        options:
          model: gpt-image-1

upload:
  path: C:\\code\\springai                   

  
  
  
  
  
  
  
  